[package]
name = "peroxyde-ir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id-arena = "2.2.1"
num-bigint = "0.4.3"
paste = "1.0.7"
seq-macro = "0.3.0"
typed-arena = "2.0.1"
